from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

from validate_skill_repo import REPO_ROOT, parse_frontmatter, parse_openai_yaml


DEFAULT_OUTPUT = REPO_ROOT / "reports" / "skill-inventory.md"


def skill_category(skill_path: Path) -> str:
    relative = skill_path.relative_to(REPO_ROOT)
    if relative.parent == Path("."):
        return "root"
    return relative.parts[0]


def inventory_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for skill_file in sorted(REPO_ROOT.rglob("SKILL.md")):
        frontmatter = parse_frontmatter(skill_file)
        metadata_path = skill_file.parent / "agents" / "openai.yaml"
        metadata = parse_openai_yaml(metadata_path) if metadata_path.exists() else {}

        rows.append(
            {
                "path": skill_file.relative_to(REPO_ROOT).as_posix(),
                "category": skill_category(skill_file),
                "skill_name": frontmatter["name"],
                "display_name": metadata.get("display_name", ""),
                "metadata": "yes" if metadata_path.exists() else "no",
                "description": frontmatter["description"],
            }
        )
    return rows


def render_inventory(rows: list[dict[str, str]]) -> str:
    total = len(rows)
    with_metadata = sum(1 for row in rows if row["metadata"] == "yes")
    by_category = Counter(row["category"] for row in rows)
    metadata_by_category = Counter(
        row["category"] for row in rows if row["metadata"] == "yes"
    )

    lines: list[str] = []
    lines.append("# Skill Inventory")
    lines.append("")
    lines.append(
        "This report is generated by `python scripts/generate_skill_inventory.py`."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total skills: `{total}`")
    lines.append(f"- Skills with `agents/openai.yaml`: `{with_metadata}/{total}`")
    lines.append("")
    lines.append("## Coverage By Area")
    lines.append("")
    lines.append("| Area | Skills | Metadata Coverage |")
    lines.append("|---|---:|---:|")
    for category in sorted(by_category):
        lines.append(
            f"| `{category}` | {by_category[category]} | {metadata_by_category.get(category, 0)}/{by_category[category]} |"
        )
    lines.append("")
    lines.append("## Skill Table")
    lines.append("")
    lines.append("| Path | Skill Name | Display Name | Area | Metadata |")
    lines.append("|---|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{row['path']}` | `{row['skill_name']}` | {row['display_name']} | `{row['category']}` | {row['metadata']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()

    content = render_inventory(inventory_rows())

    if args.check:
        check_path = args.check.resolve()
        expected = check_path.read_text(encoding="utf-8") if check_path.exists() else ""
        if expected != content:
            print(f"Inventory report is stale: {check_path.relative_to(REPO_ROOT)}")
            return 1
        print(f"Inventory report is up to date: {check_path.relative_to(REPO_ROOT)}")
        return 0

    output_path = args.write
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Wrote inventory report to {output_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
